auto: true
server: true
permalink: /blog/:year/:month/:day/:title.html
baseurl: ""
exclude:
- .gitignore
- README.md

prose:
  rooturl: "_posts"
  metadata:
    _posts/articles:
      permalink: :title.html
