auto: true
server: true
baseurl: ""
exclude:
- .gitignore
- README.md

prose:
  rooturl: "_posts"
  metadata:
    _posts/:
      permalink: /blog/:year/:month/:day/:title.html
    _posts/articles:
      permalink: /test/:year/:month/:day/:title.html
